stages:
   - build
   - deploy

# build stage
build_app:
   image: node:alpine
   stage: build
   only:
      - dev
   script:
      - npm install
      - npm run build
   cache:
     paths:
       - node_modules/
   artifacts:
      paths:
         # build folder
         - dist/
      expire_in: 1 hour

# production stage
production:
   image: python:alpine
   stage: deploy
   only:
      - dev
   script:
      - pip install awscli
      - aws configure set aws_access_key_id "$ACCESS_KEY_ID"
      - aws configure set aws_secret_access_key "$SECRET_ACCESS_KEY"
      - aws configure set default.region "$REGION"
      - aws --endpoint-url=https://storage.yandexcloud.net s3 rm s3://test.leadersmanagement.com --recursive
      - aws --endpoint-url=https://storage.yandexcloud.net s3 sync ./dist/ s3://test.leadersmanagement.com
      - echo "end"

